DYNAMIXEL_RQ_PING					=0x01
DYNAMIXEL_RQ_READ_DATA		=0x02
DYNAMIXEL_RQ_WRITE_DATA		=0x03
DYNAMIXEL_RQ_REG_WRITE		=0x04
DYNAMIXEL_RQ_REG_ACTION		=0x05
DYNAMIXEL_RQ_RESET				=0x06
DYNAMIXEL_RQ_SYNC_WRITE		=0x83


DYNAMIXEL_RQ_ZMQ_ECHO			=0xF0
